### ISSUE TITLE
A problem in computeSatElevAzimuth_fromNav.py

### ISSUE THREAD

**Issue by ConorLuo** [paarnes/GNSS_Multipath_Analysis_Software#9]
I followed the most simple example and ran the code :

from GNSS_MultipathAnalysis import GNSS_MultipathAnalysis
rinObs_file = r'C:\...\ObservationFiles\OBS0526.obs'
nav_file    = r'C:\...\NavigationFiles\NAV0526.nav'
analysisResults = GNSS_MultipathAnalysis(rinObs_file, broadcastNav1=nav_file)

In fact I tried different Obs_file and nav_file generated from u-blox and Sino GNSS receivers,but The same problem occurred in the same file computeSatElevAzimuth_fromNav.py ：

Traceback (most recent call last):
  File "C:\...\GNSS_MultipathAnalysis.py", line 281, in GNSS_MultipathAnalysis
    sat_pos = computeSatElevAzimuth_fromNav(nav_files,approxPosition,GNSS_SVs,GNSS_obs,time_epochs,tLim_GEC,tLim_R)
  File "C:\...\computeSatElevAzimuth_fromNav.py", line 87, in computeSatElevAzimuth_fromNav
    ephemerides = ephemerides.astype(float)
ValueError: could not convert string to float: '-.217760913074D-03'

rinex version is 3.04.Nav file format is the same, and I have tried to delete the values reported in error, but I have found that all the data in the nav file cannot be converted to float,could you please tell me how to solve it?thank you!

**Comment by paarnes** [comment]
Hi,
Thank you for your feedback. It seems to be a problem with the reading routing for rinex navigation files. It would be great if you could share the file which is failing by mail so I can do some debugging. Great if you also add the observation file, so I can run it throught the software.

E-mail: per.helge.aarnes@gmail.com

Best regards,
Per Helge

**Comment by paarnes** [comment]
Hi again,

The problem was that the navigation file contained D notation for exponential form. This is a fortran notation. Today it's more common to use E to represent exponential form.  I was not aware that this notation was used by Rinex 3. However, I have now fix this issue in the reading routing for navigation file where D get replaced by E if found. I have tested the software on your files, and it now runs without any problems. Just pull the latest code from the master branch and try again. 

FIX: #5f1e441
Please let me know if you run into more challenges. 

Best regards,
Per Helge
